// Transkripsi "Kertas Kerja Pusdiklat MR 2024" (Pusat Pendidikan dan Pelatihan BPS)
// Kategori, sumber, kemungkinan, levelDampak, levelRisiko divalidasi terhadap referensi DB.

export const SASARAN =
  "Meningkatkan layanan pelatihan yang sesuai dengan perkembangan ilmu pengetahuan, teknologi informasi mutakhir dan aturan yang berlaku";
export const KEGIATAN = "Penyelenggaraan Pelatihan Pusdiklat BPS";

export type Kategori = "Operasional" | "Kepatuhan" | "Kebijakan";
export type Sumber = "Internal" | "Eksternal";
export type Efektif = "efektif" | "kurang efektif" | "tidak efektif";

export interface RiskRec {
  no: number;
  step: string;
  risiko: string;
  penyebab: string | null;
  dampak: string | null;
  kategori: Kategori;
  sumber: Sumber;
  kemungkinan: string;
  levelDampak: string;
  levelRisiko: string;
  pengendalian: string;
  efektivitas: Efektif;
  respon: string | null;
}

const R = (
  no: number, step: string, risiko: string, penyebab: string | null, dampak: string | null,
  kategori: Kategori, sumber: Sumber, kemungkinan: string, levelDampak: string,
  levelRisiko: string, pengendalian: string, efektivitas: Efektif, respon: string | null
): RiskRec => ({ no, step, risiko, penyebab, dampak, kategori, sumber, kemungkinan, levelDampak, levelRisiko, pengendalian, efektivitas, respon });

export const risks: RiskRec[] = [
  // ===== Analisis Kebutuhan Pelatihan =====
  R(1, "Perumusan masalah dalam Analisis Kebutuhan Pelatihan (AKP)", "Tidak terdapat standar kompetensi", "Kurangnya koordinasi dengan stakeholder terkait", "Tidak mencerminkan akar penyebab masalah", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "melibatkan semua pihak yang terlibat", "tidak efektif", "Mengurangi Risiko"),
  R(1, "Perumusan masalah dalam Analisis Kebutuhan Pelatihan (AKP)", "Kurangnya data kompetensi yang dimiliki oleh pegawai", "Belum optimalnya pembaruan (updating) data kompetensi pegawai", "pemahaman yang kurang mendalam terhadap masalah yang sebenarnya terjadi", "Operasional", "Internal", "Jarang Terjadi", "Minor", "Rendah", "melibatkan seluruh pegawai dalam memperbaharui kompetensi", "tidak efektif", "Mengurangi Risiko"),
  R(2, "Perumusan tujuan dalam Analisis Kebutuhan Pelatihan", "tujuan tidak sesuai dengan kebutuhan", "Tujuan analisis tidak sesuai dengan peruntukannya", "kesulitan dalam mengukur keberhasilan pelatihan", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "membuat tujuan yang spesifik dan terukur", "efektif", "Mengurangi Risiko"),
  R(2, "Perumusan tujuan dalam Analisis Kebutuhan Pelatihan", "tujuan terlalu spesifik", "Kurangnya keterlibatan stakeholder", "tujuan tidak sesuai dengan kebutuhan", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "melakukan evaluasi dan pemantauan terhadap kebutuhan pelatihan", "efektif", "Mengurangi Risiko"),
  R(3, "Pengembangan instrumen dalam Analisis Kebutuhan Pelatihan", "Instrumen tidak mengukur dengan tepat (tidak valid)", "instrumen belum diuji validitasnya", "ketidaktepatan mendapatkan ukuran keberhasilan pelatihan", "Operasional", "Internal", "Jarang Terjadi", "Minor", "Rendah", "memastikan instrumen yang dikembangkan valid", "kurang efektif", "Mengurangi Risiko"),
  R(3, "Pengembangan instrumen dalam Analisis Kebutuhan Pelatihan", "instrumen tidak mampu menggali kebutuhan pelatihan secara menyeluruh", "kurangnya beragamnya sampel", "data yang tidak akurat dan mendapatkan kesimpulan yang salah", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "instrumen harus dirancang sebaik mungkin", "kurang efektif", "Mengurangi Risiko"),
  R(4, "Pengumpulan data dalam Analisis Kebutuhan Pelatihan", "Kualitas data yang kurang baik", "kurang lengkapnya isian pada kuesioner", "menghambat identifikasi kebutuhan pelatihan yang tepat", "Operasional", "Eksternal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "Melakukan kontrol kualitas data", "kurang efektif", "Mengurangi Risiko"),
  R(4, "Pengumpulan data dalam Analisis Kebutuhan Pelatihan", "Bias dalam menjawab pertanyaan instrumen", "memiliki kepentingan", "pelatihan tidak sesuai dengan kebutuhan", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "Melatih petugas pengumpul data", "tidak efektif", "Mengurangi Risiko"),
  R(5, "Pengolahan data dalam Analisis Kebutuhan Pelatihan", "Kesalahan dalam menginput data", "ketidakcermatan dalam menginput data", "hasil analisis tidak akurat", "Operasional", "Internal", "Hampir Tidak Terjadi", "Moderat", "Sangat Rendah", "Memvalidasi data input", "efektif", "Mengurangi Risiko"),
  R(5, "Pengolahan data dalam Analisis Kebutuhan Pelatihan", "Ketidaklengkapan isian data", "belum adanya konsistensi di dalam program pengolah data", "interpretasi data kurang tepat", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "Meningkatkan kapasitas pengolahan data", "kurang efektif", "Mengurangi Risiko"),
  R(6, "Penafsiran hasil dalam Analisis Kebutuhan Pelatihan", "Subjektifitas dalam menafsirkan hasil", "sudah memiliki kepentingan", "kompetensi yang akan ditingkatkan tidak sesuai kebutuhan", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "melakukan triangulasi data", "efektif", "Mengurangi Risiko"),
  R(6, "Penafsiran hasil dalam Analisis Kebutuhan Pelatihan", "Kurangnya partisipasi stakeholder dalam interpretasi", "belum optimalnya sosialisasi hasil", "interpretasi hasil tidak sesuai dengan kebutuhan stakeholder", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "Melibatkan stakeholders dalam proses interpretasi", "kurang efektif", "Mengurangi Risiko"),
  R(7, "Pelaporan Analisis Kebutuhan Pelatihan", "Ketidaklengkapan informasi dan visualisasinya", "kurangnya pemahaman dalam penyusunan laporan", "membatasi pemahaman pola kompetensi", "Operasional", "Internal", "Hampir Tidak Terjadi", "Moderat", "Sangat Rendah", "Memastikan kelengkapan informasi dan visualisasinya", "efektif", "Mengurangi Risiko"),
  R(7, "Pelaporan Analisis Kebutuhan Pelatihan", "Penyampaian laporan yang tidak efektif", "kegagalan dalam menyimpulkan dan merekomendasikan", "menghambat pengambilan keputusan", "Operasional", "Internal", "Sering Terjadi", "Tidak Signifikan", "Rendah", "Menyampaikan kesimpulan dan rekomendasi dengan jelas", "kurang efektif", "Mengurangi Risiko"),
  R(8, "Menentukan Tujuan Kurikuler Umum (TKU) atau Kompetensi Dasar dalam rancang bangun program pelatihan", "Tingkat Kesulitan TKU dan KD yang Tidak Tepat", "kurang tepatnya analisis kesenjangan kompetensi", "tidak memberikan nilai tambah bagi peserta", "Operasional", "Internal", "Hampir Pasti Terjadi", "Tidak Signifikan", "Rendah", "Melakukan uji coba TKU dan KD", "efektif", "Mengurangi Risiko"),
  R(8, "Menentukan Tujuan Kurikuler Umum (TKU) atau Kompetensi Dasar dalam rancang bangun program pelatihan", "Keterbatasan sumber daya (waktu, anggaran dan keahlian)", "perencanaan yang kurang optimal", "program pelatihan kurang berkualitas", "Operasional", "Internal", "Sering Terjadi", "Minor", "Sedang", "Memastikan ketersediaan sumber daya", "kurang efektif", "Mengurangi Risiko"),
  R(9, "Menetapkan tujuan kurikuler khusus atau Indikator Keberhasilan dalam rancang bangun program pelatihan (RBPP)", "Penetapan Indikator Keberhasilan yang tidak relevan", "kurangnya partisipasi stakeholder", "indikator keberhasilan tidak relevan dengan kebutuhan dan ekspektasi", "Operasional", "Internal", "Hampir Pasti Terjadi", "Tidak Signifikan", "Rendah", "Memastikan kejelasan tujuan program pelatihan", "kurang efektif", "Mengurangi Risiko"),
  R(9, "Menetapkan tujuan kurikuler khusus atau Indikator Keberhasilan dalam rancang bangun program pelatihan (RBPP)", "Penetapan Indikator Keberhasilan yang tidak terukur", "kurangnya pemahaman tentang penetapan indikator yang terukur", "menyulitkan evaluasi program pelatihan", "Operasional", "Internal", "Jarang Terjadi", "Minor", "Rendah", "Melibatkan stakeholders dalam proses penetapan Indikator Keberhasilan", "efektif", "Mengurangi Risiko"),
  R(10, "Identifikasi dan analisis materi mata ajaran", "Ketidaksesuaian materi dengan rancang bangun program pelatihan", "kurangnya pemahaman tentang kerangka kurikulum", "materi yang dihasilkan tidak terstruktur", "Operasional", "Internal", "Sering Terjadi", "Tidak Signifikan", "Rendah", "Memahami kerangka kurikulum", "efektif", "Mengurangi Risiko"),
  R(10, "Identifikasi dan analisis materi mata ajaran", "Ketidaksesuaian materi dengan perkembangan peserta (terlalu mudah atau terlalu sulit)", "kurangnya uji coba materi", "peserta tidak mendapatkan pembelajaran yang tepat", "Operasional", "Internal", "Hampir Pasti Terjadi", "Tidak Signifikan", "Rendah", "mencari referensi untuk menyusun materi", "tidak efektif", "Mengurangi Risiko"),
  R(11, "Memilih metoda yang efektif, alat bantu yang sesuai, estimasi waktu dan evaluasi", "Ketidaktepatan metode pembelajaran dan evaluasinya", "Kurangnya pengetahuan tentang metode pembelajaran dan evaluasinya", "peserta kurang terlibat dalam pembelajaran", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "memilih metode pelatihan yang sesuai", "kurang efektif", "Mengurangi Risiko"),
  R(11, "Memilih metoda yang efektif, alat bantu yang sesuai, estimasi waktu dan evaluasi", "Ketidaktepatan alat bantu dan estimasi waktu", "keterbatasan alat bantu", "menghambat proses pembelajaran", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "memilih alat bantu yang efektif", "efektif", "Mengurangi Risiko"),
  R(12, "Menyusun struktur program dan diagram alur proses pembelajaran", "Ketidaksesuaian struktur program dengan tujuan", "ketidakjelasan tujuan program pelatihan", "peserta tidak memahami materi dengan baik", "Operasional", "Internal", "Jarang Terjadi", "Moderat", "Rendah", "memastikan struktur program pelatihan yang jelas", "kurang efektif", "Mengurangi Risiko"),
  R(12, "Menyusun struktur program dan diagram alur proses pembelajaran", "Ketidaklengkapan diagram alur proses pembelajaran", "kurangnya pemahaman tentang diagram alur proses pembelajaran", "fasilitator kesulitan dalam menyampaikan materi pelatihan", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "membuat proses pembelajaran yang jelas", "tidak efektif", "Mengurangi Risiko"),
  R(13, "Membuat Rancang Bangun Pembelajaran Mata Pelatihan (RBPMP)", "Ketidaksesuaian RBPMP dengan RBPP", "kurang memahami RBPP", "peserta tidak mendapatkan kompetensi yang dibutuhkan", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "memahami RBPP dengan baik dan jelas", "tidak efektif", "Mengurangi Risiko"),
  R(13, "Membuat Rancang Bangun Pembelajaran Mata Pelatihan (RBPMP)", "Ketidaklengkapan RBPMP", "kurangnya pengetahuan menyusun RBPMP", "fasilitator dan peserta tidak dapat bersinergi dalam pembelajaran", "Operasional", "Internal", "Hampir Tidak Terjadi", "Moderat", "Sangat Rendah", "menambah pengetahuan tentang RBPMP", "efektif", "Mengurangi Risiko"),
  R(14, "Menengumpulkan bahan referensi dalam menyusun modul mata pelatihan", "Ketidaktepatan pemilihan sumber referensi", "kurangnya luasnya pengetahuan", "materi tidak akurat dan tidak dapat diandalkan (tidak fokus)", "Operasional", "Internal", "Jarang Terjadi", "Minor", "Rendah", "membuat daftar sumber bahan referensi", "efektif", "Mengurangi Risiko"),
  R(14, "Menengumpulkan bahan referensi dalam menyusun modul mata pelatihan", "Keterbatasan sumber daya (buku)", "keterbatasan akses sumber daya", "penulis terkendala dalam menyusun materi modul pelatihan", "Operasional", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "melakukan studi pustaka pada perpustakaan", "kurang efektif", "Mengurangi Risiko"),
  R(15, "Menyusun materi mata pelatihan dengan jelas, ringkas, dan mudah dipahami oleh peserta", "Ketidakjelasan struktur dan isi materi", "kurangnya pemahaman tentang struktur materi", "peserta kesulitan dalam mengikuti materi", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "meningkatkan pemahaman tentang struktur materi", "kurang efektif", "Mengurangi Risiko"),
  R(15, "Menyusun materi mata pelatihan dengan jelas, ringkas, dan mudah dipahami oleh peserta", "Kurangnya penggunaan bahasa yang jelas dan mudah dipahami", "penggunaan bahasa yang terlalu teknis dan ilmiah", "peserta tidak mudah memahami materi, terutama peserta dengan latar belakang yang berbeda dengan isi materi", "Operasional", "Internal", "Sering Terjadi", "Tidak Signifikan", "Rendah", "melibatkan pihak lain untuk memberikan saran dan masukan terhadap isi materi", "kurang efektif", "Mengurangi Risiko"),
  R(16, "Menyusun pedoman penyelenggaraan pelatihan", "Ketidaklengkapan informasi pada pedoman", "kurangnya bahan referensi penyusunan pedoman", "kurangnya sinergi antara fasilitator, penyelenggara dan peserta", "Kepatuhan", "Internal", "Hampir Tidak Terjadi", "Signifikan", "Rendah", "mengadakan sosialisasi pedoman penyelenggaraan", "efektif", "Mengurangi Risiko"),
  R(16, "Menyusun pedoman penyelenggaraan pelatihan", "Ketidakjelasan peran dan tanggungjawab (prosedur dan aturan pelatihan)", "kurangnya komunikasi dengan stakeholder dalam proses penyusunan", "penyelenggara dan peserta kesulitan dalam melaksanakan pelatihan", "Kepatuhan", "Internal", "Sering Terjadi", "Signifikan", "Tinggi", "membuat kerangka kerja", "efektif", "Mengurangi Risiko"),
  // ===== Usulan Penyelenggaraan Pelatihan =====
  R(17, "Kedeputian Bidang Teknis (eksternal Pusdiklat/BPS) mengajukan permintaan fasilitasi penyelenggaraan pelatihan kepada Sestama", "Usulan Pelatihan yang diajukan kurang dari 20 hari kerja (eksternal Pusdiklat)", "Penyelenggara kurang memerhatikan ketentuan jadwal", "Pelatihan tidak disetujui namun tetap berjalan karena terkait pelaksanaan lapangan survei/sensus, sehingga mengurangi waktu pembuatan Surat Pemanggilan Peserta serta penyiapan kelas di Simdiklat dan LMS eWARKOP", "Kepatuhan", "Eksternal", "Kadang Terjadi", "Moderat", "Sedang", "mengingatkan pihak eksternal tentang ketentuan jadwal", "efektif", "Mengurangi Risiko"),
  R(17, "Kedeputian Bidang Teknis (eksternal Pusdiklat/BPS) mengajukan permintaan fasilitasi penyelenggaraan pelatihan kepada Sestama", "Usulan Pelatihan belum tersedia anggarannya di POK Pusdiklat", "Tidak diusulkan saat IPLAN/SIREKA; Adanya permintaan Adhoc", "Pelatihan tidak terlaksana atau terlaksana dengan mengorbankan pelatihan lain yang dianggap kurang prioritas", "Kebijakan", "Eksternal", "Kadang Terjadi", "Moderat", "Sedang", "Koordinasi dengan eksternal pelatihan-pelatihan yang akan dilaksanakan; Koordinasi dengan Biroren", "efektif", "Mengurangi Risiko"),
  R(18, "Pejabat yang berwenang memberikan persetujuan (approval) pelatihan melalui Simdiklat", "Proses approval belum otomatis", "Kedeputian terkait mengajukan Surat Usulan Pelatihan ke Sekretaris Sestama, menunggu dispo Sestama, kemudian PIC UKK mengunggah disposisi dan mengapprove permohonan penyelenggaraan diklat", "Proses surat usulan yang belum otomatis mengakibatkan harus menghubungi Sekretaris dan Tim UKK Sestama secara manual", "Operasional", "Eksternal", "Sering Terjadi", "Moderat", "Tinggi", "Koordinasi dengan pihak terkait", "kurang efektif", "Mengurangi Risiko"),
  // ===== Persiapan Pelatihan =====
  R(19, "PIC/Admin Bangkom melakukan entri usulan peserta pelatihan, jadwal pelatihan, pengajar serta mengunggah KAK sesuai standar", "Jadwal menunjukkan Jumlah Jam Pelajaran yang belum memenuhi standar 2:1 untuk Jam Pelatihan Sinkronus berbanding Asinkronus", "Tim PJK menetapkan substansi mata pelatihan yang hampir seluruhnya dibahas selama PJJ, karena persepsinya Pembelajaran Sinkronus lebih efektif dibanding Asinkronus", "Kualitas pembelajaran tidak optimal, karena peserta kelelahan sinkronus dan kurang praktek untuk memperdalam pemahaman", "Operasional", "Eksternal", "Hampir Pasti Terjadi", "Signifikan", "Tinggi", "mengadakan rapat pengajar sebelum PJJ dimulai", "efektif", "Mengurangi Risiko"),
  R(19, "PIC/Admin Bangkom melakukan entri usulan peserta pelatihan, jadwal pelatihan, pengajar serta mengunggah KAK sesuai standar", "KAK Pelatihan belum mendetailkan penggunaan biaya", "Belum paham dengan KAK Penyelenggaraan Pelatihan, khususnya terkait pembiayaan yang dikeluarkan (honor fasilitator, termasuk honor penceramah)", "Penyelenggara SM melengkapi data penggunaan anggaran sesuai dengan aturan yang berlaku", "Operasional", "Eksternal", "Kadang Terjadi", "Moderat", "Tinggi", "Reviu KAK dari PPK, hasilnya ditindaklanjuti oleh PIC Pelatihan", "kurang efektif", "Mengurangi Risiko"),
  R(19, "PIC/Admin Bangkom melakukan entri usulan peserta pelatihan, jadwal pelatihan, pengajar serta mengunggah KAK sesuai standar", "Manajer Kelas telat dalam menginput nama calon peserta di Simdiklat", "PIC BPS Provinsi atau PIC BPS Kabupaten telat menyampaikan nama peserta, akibat sulit menetapkan peserta karena tumpang tindih beban kerja SDM di unit kerja eselon 3 atau 2", "Terlambatnya surat pemanggilan peserta yang seharusnya pada H-5 sebelum MOOC dan terlambatnya registrasi peserta di Simdiklat dan LMS E-WARKOP", "Operasional", "Eksternal", "Kadang Terjadi", "Moderat", "Sangat Rendah", "Mengingatkan penyelenggara eksternal untuk lebih awal dalam koordinasi dengan eselon 2 atau 3 mengenai penetapan peserta pelatihan", "kurang efektif", "Mengurangi Risiko"),
  R(19, "PIC/Admin Bangkom melakukan entri usulan peserta pelatihan, jadwal pelatihan, pengajar serta mengunggah KAK sesuai standar", "Simdiklat menolak pengusulan peserta yang sudah terdaftar pada pelatihan lain", "Jadwal suatu pelatihan yang beririsan dengan pelatihan yang lainnya", "Admin Bangkom tidak bisa mendaftarkan calon peserta ke Simdiklat", "Operasional", "Eksternal", "Kadang Terjadi", "Minor", "Rendah", "Menghubungi Tim IT untuk didaftarkan", "tidak efektif", "Membagi Risiko"),
  R(19, "PIC/Admin Bangkom melakukan entri usulan peserta pelatihan, jadwal pelatihan, pengajar serta mengunggah KAK sesuai standar", "PJJ pada kelas gabungan beberapa provinsi dianggap tidak efektif", "Jumlah peserta pelatihan minimal 25 orang per kelas, sehingga provinsi yang pesertanya sedikit dibuat kelas gabungan", "Perbedaan karakteristik antar provinsi mengakibatkan diskusi tidak bisa spesifik membahas kendala di masing-masing provinsi", "Operasional", "Internal", "Sering Terjadi", "Moderat", "Sedang", "Memfasilitasi diskusi dalam kelompok kecil (sesuai provinsi) untuk membahas hal-hal spesifik", "kurang efektif", "Mengurangi Risiko"),
  R(20, "PIC/Admin Bangkom Penyelenggara berkolaborasi dengan Tim E-WARKOP mempersiapkan kelas pelatihan dan bahan pembelajaran", "Tim PJK tidak mengumpulkan bahan pembelajaran sesuai waktu yang ditetapkan, serta masih terdapat revisi bahan ajar pada saat MOOC/PJJ berlangsung", "Tim PJK kurang memberikan jeda waktu antara workshop intama dengan pelatihan innas, padahal setelah workshop intama masih membutuhkan waktu melakukan revisi bahan pembelajaran", "Tim E-WARKOP menggunakan waktu di luar jam/hari kerja untuk memfinalkan kelas pelatihan agar pembelajaran berlangsung sesuai jadwal; proses cek dan ricek kelas sebelum pelatihan dilakukan dalam waktu singkat sehingga masih ada perbaikan saat MOOC berlangsung", "Operasional", "Eksternal", "Kadang Terjadi", "Moderat", "Tinggi", "Kelas Pelatihan E-WARKOP tetap diproses mendekati waktu pelatihan meskipun di luar jam/hari kerja agar kelas tetap berlangsung sesuai jadwal; menyesuaikan kelengkapan kelas pembelajaran di E-WARKOP", "efektif", "Mengurangi Risiko"),
  R(20, "PIC/Admin Bangkom Penyelenggara berkolaborasi dengan Tim E-WARKOP mempersiapkan kelas pelatihan dan bahan pembelajaran", "Format penulisan soal-soal yang disiapkan Tim PJK tidak sesuai format Moodle, sehingga memerlukan waktu pengecekan soal dan penyesuaian format", "Terjadi kesalahpahaman atau miskomunikasi antara PIC Admin Bangkom Penyelenggara dan Tim E-WARKOP terkait format soal dan/atau jadwal penyerahan soal", "Format soal yang masih salah pada sesi Pretest/Kuis dijadikan soal bonus", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "Tim E-WARKOP sudah memberitahukan format soal pada saat rapat persiapan pelatihan", "kurang efektif", "Mengurangi Risiko"),
  R(20, "PIC/Admin Bangkom Penyelenggara berkolaborasi dengan Tim E-WARKOP mempersiapkan kelas pelatihan dan bahan pembelajaran", "Masih dilakukan edit atau penyesuaian jadwal pelatihan pada saat PJJ", "Pengajar memiliki beban kerja yang tumpang tindih sehingga ada penugasan mendadak yang jadwalnya beririsan dengan jadwal yang ditetapkan penyelenggara", "Dilakukan penyesuaian jadwal atau pengajar saat PJJ berlangsung", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "Dilakukan rapat pengajar sebelum pelatihan dilaksanakan", "kurang efektif", "Mengurangi Risiko"),
  R(20, "PIC/Admin Bangkom Penyelenggara berkolaborasi dengan Tim E-WARKOP mempersiapkan kelas pelatihan dan bahan pembelajaran", "Jadwal realisasi saat PJJ tidak diupdate pada Simdiklat dan E-WARKOP", "Manajer kelas terlupa/terlewat sehingga tidak melakukan update jadwal pengajar dan jumlah jam pelatihan (JP)", "Terdapat perbedaan jumlah JP pengajar yang baru diketahui saat pengajar mendapat transfer honor", "Operasional", "Eksternal", "Kadang Terjadi", "Moderat", "Rendah", "Tim keuangan sudah memberikan draft SPJ ke WAG Pengajar untuk di recheck ketepatan JP dan data di SPJ tersebut", "efektif", "Mengurangi Risiko"),
  R(21, "Surat Pemanggilan peserta pelatihan di email ke satker eselon 2, maksimal H-5 sebelum MOOC", "Keterlambatan peserta dalam menerima surat pemanggilan peserta pelatihan", "Tim PJK terlambat menerima usulan peserta pelatihan dari satker BPS Selindo, sehingga lambat menginput calon peserta ke Simdiklat dan PIC Pusdiklat terlambat memproses surat pemanggilan peserta", "Peserta terlambat registrasi di Simdiklat untuk melengkapi data serta mengunggah Surat Tugas dan Foto, terlambat join di WAG Pelatihan dan Self Enrolment ke E-WARKOP", "Kepatuhan", "Eksternal", "Jarang Terjadi", "Minor", "Sedang", "Manajer kelas memeriksa kelengkapan peserta dan mengingatkan untuk segera melengkapi", "kurang efektif", "Mengurangi Risiko"),
  R(22, "Registrasi peserta pelatihan di Simdiklat paling lambat hari pertama MOOC", "Terjadi penggantian peserta pada pertengahan MOOC atau pada sesi PJJ", "Peserta mengalami gangguan kesehatan, anggota keluarga meninggal, atau ada pekerjaan adhoc yang harus dilakukan", "Peserta pengganti mungkin kesulitan mengikuti materi yang telah disampaikan; kualitas pembelajaran dapat terganggu jika peserta pengganti tidak dapat beradaptasi dengan cepat", "Operasional", "Eksternal", "Jarang Terjadi", "Minor", "Sangat Rendah", "Melakukan recording setiap sesi mata pelatihan dan playlist-nya diinformasikan pada kelas Pelatihan di E-WARKOP; menyiapkan prosedur penggantian peserta disertai surat penggantian yang ditandatangani oleh JPT Pertama (Pejabat Eselon 2)", "efektif", "Mengurangi Risiko"),
  R(23, "Proses validasi data yang diisi calon peserta beserta surat tugas dan foto, serta pengecekan jadwal pelatihan dan nama pengajar", "Peserta kurang teliti dalam menginput datanya dan/atau tidak mengupdate data profil sesuai kondisi terkini", "Peserta kurang perduli tentang kelengkapan data dan akurasinya", "Data peserta tidak akurat dan baru diprotes saat peserta mendownload sertifikat, padahal saat sertifikat sudah di e-sign tidak bisa direvisi", "Operasional", "Eksternal", "Kadang Terjadi", "Signifikan", "Sedang", "SOP menyatakan peserta harus mengisi biodata dengan lengkap dan kondisi terkini; manajer kelas menyampaikan agar peserta melakukan preview sebelum sertifikat diproses e-sign", "kurang efektif", "Mengurangi Risiko"),
  // ===== MOOC =====
  R(24, "Bahan Pembelajaran sudah tersedia di kelas E-WARKOP", "Bahan ajar masih ada yang di-update saat MOOC", "Adanya revisi substantif pada bahan ajar", "Peserta kebingungan akan file mana yang terkini", "Operasional", "Eksternal", "Kadang Terjadi", "Minor", "Rendah", "File revisi dibedakan namanya dengan file yang sudah diunggah sebelum MOOC dimulai", "efektif", "Mengurangi Risiko"),
  R(25, "Selama MOOC, peserta melakukan pembelajaran mandiri sekurangnya 3 JP/hari", "Peserta tidak menggunakan masa MOOC untuk melakukan pembelajaran mandiri sesuai ketentuan", "Beban kerja terlalu tinggi, belum memanfaatkan waktu secara optimal dan kurangnya dukungan dari atasan", "Peserta tidak memiliki pengetahuan awal terkait materi yang akan didiskusikan selama PJJ", "Operasional", "Eksternal", "Sering Terjadi", "Signifikan", "Tinggi", "Dianjurkan kepada penyelenggara pelatihan untuk mengalokasikan materi harian selama MOOC dan diakhiri kuis harian; pada surat pemanggilan peserta dicantumkan agar atasan membebastugaskan peserta selama masa pelatihan", "kurang efektif", "Menerima Risiko"),
  R(25, "Selama MOOC, peserta melakukan pembelajaran mandiri sekurangnya 3 JP/hari", "Bahan Pembelajaran MOOC belum disediakan dalam format video pembelajaran yang menarik dan mudah dipahami", "Kurangnya kreativitas dalam pembuatan materi, tidak adanya standar kualitas, keterbatasan sumber daya", "Motivasi belajar peserta menurun, pemahaman konsep sulit", "Operasional", "Eksternal", "Sering Terjadi", "Signifikan", "Tinggi", "Menganjurkan Tim Penyelenggara untuk membuat video tutorial bahan pembelajaran", "tidak efektif", "Mengurangi Risiko"),
  R(25, "Selama MOOC, peserta melakukan pembelajaran mandiri sekurangnya 3 JP/hari", "Kurangnya interaksi antara peserta dan pengajar", "Penyelenggara belum menyediakan fitur interaktif di kelas E-WARKOP untuk memfasilitasi pertanyaan dari peserta agar segera direspon oleh pengajar", "Peserta kesulitan memahami konsep dalam buku pedoman untuk dikaitkan dengan konteks di wilayahnya, sehingga kurang termotivasi untuk belajar mandiri", "Operasional", "Eksternal", "Sering Terjadi", "Signifikan", "Tinggi", "Menyediakan Fitur QnA namun masih belum interaktif karena tidak langsung direspon oleh pengajar", "kurang efektif", "Mengurangi Risiko"),
  // ===== PJJ =====
  R(26, "Presensi Harian peserta/fasilitator dilakukan 1 kali hingga pukul 15.00 WIB melalui menu Attendance di E-WARKOP", "Peserta/fasilitator tidak melakukan presensi pada menu attendance sesuai waktu yang ditetapkan atau bahkan tidak melakukan presensi", "Peserta/fasilitator lupa presensi atau adanya gangguan jaringan", "Data kehadiran menjadi tidak akurat dan mengurangi nilai sikap perilaku pada aspek disiplin", "Operasional", "Eksternal", "Kadang Terjadi", "Minor", "Rendah", "Ketua kelas bertugas mengingatkan peserta/fasilitator melakukan presensi dan Manajer Kelas melakukan monitoring harian termasuk memastikan kelengkapan attendance peserta", "efektif", "Mengurangi Risiko"),
  R(27, "Pretest dikerjakan secara mandiri oleh peserta sebelum pembelajaran dimulai", "Gangguan akses pretest, khususnya saat pelatihan yang pesertanya massive dan berasal dari seluruh Indonesia", "Koneksi internet peserta yang tidak memadai", "Peserta mengalami kesulitan mengakses pretest", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "Penyelenggara menganjurkan peserta untuk memastikan koneksi internet yang memadai", "efektif", null),
  R(27, "Pretest dikerjakan secara mandiri oleh peserta sebelum pembelajaran dimulai", "Server down saat diakses oleh banyak user di waktu bersamaan", "Kapasitas server yang terbatas", "Peserta mengalami loading lambat atau bahkan tidak dapat mengikuti pretest", "Operasional", "Internal", "Jarang Terjadi", "Moderat", "Rendah", "Pusdiklat telah melakukan integrasi server ke server BPS sehingga kendala server down hampir tidak terjadi lagi", "efektif", null),
  R(28, "Pembelajaran berlangsung interaktif dan fun learning", "Kurangnya interaksi dua arah pada sesi materi pelatihan", "Peserta tidak memiliki kesempatan untuk bertanya atau memberikan tanggapan terhadap materi yang disampaikan; peserta merasa bosan dengan pembelajaran yang monoton", "Peserta mungkin kesulitan memahami konsep yang kompleks atau salah menginterpretasikan materi; peserta kurang termotivasi dan hasil belajar yang diperoleh kurang optimal", "Operasional", "Eksternal", "Sering Terjadi", "Signifikan", "Tinggi", "Penyelenggara membuat QnA Form untuk diisi peserta dan direspon saat sinkronus, atau jika waktu tidak cukup fasilitator merespon di QnA; pada overview disampaikan kunci sukses pembelajaran berupa ruangan kondusif, studi kasus/role playing dan games interaktif", "kurang efektif", "Mengurangi Risiko"),
  R(28, "Pembelajaran berlangsung interaktif dan fun learning", "Fasilitator kurang menerapkan fun learning saat sesi sinkronus", "Kurangnya pengembangan keterampilan soft skills untuk penerapan fun learning; terlalu fokus pada penyampaian materi secara formal dan terburu-buru menyelesaikan materi", "Penurunan tingkat partisipasi peserta dan suasana belajar menjadi tidak kondusif; kurangnya ingatan peserta terhadap materi", "Operasional", "Eksternal", "Sering Terjadi", "Moderat", "Sedang", "Video pembelajaran orang dewasa untuk memahamkan fasilitator dalam implementasi fun learning; penyelenggara menyampaikan saat rapat persiapan agar aktivitas pembelajaran menerapkan fun learning dan bahan tayang PJJ tidak memuat semua teori", "kurang efektif", "Mengurangi Risiko"),
  R(28, "Pembelajaran berlangsung interaktif dan fun learning", "Peserta tidak mengaktifkan kamera pada sesi sinkronus", "Kurang memahami pentingnya mengaktifkan kamera", "Fasilitator sulit mengelola kelas dan menilai pemahaman peserta serta mengurangi akuntabilitas peserta", "Operasional", "Eksternal", "Sering Terjadi", "Signifikan", "Tinggi", "Fasilitator mengajak peserta untuk mengaktifkan kamera dengan memberikan contoh dan menjelaskan manfaatnya", "kurang efektif", "Mengurangi Risiko"),
  R(28, "Pembelajaran berlangsung interaktif dan fun learning", "Belum optimalnya penggunaan media pembelajaran berbasis digital", "Kurangnya pelatihan berbasis digital bagi fasilitator; fasilitator membutuhkan waktu lebih untuk menyiapkan bahan pembelajaran berbasis digital", "Lambatnya pengembangan pembelajaran berbasis digital; kualitas bahan pembelajaran kurang optimal", "Operasional", "Internal", "Sering Terjadi", "Signifikan", "Tinggi", "Pelatihan dengan sub tema pembelajaran digital telah dilakukan namun jumlah peserta masih terbatas; SOP penyiapan bahan ajar telah ditetapkan pada H-3 sebelum kelas sinkronus", "kurang efektif", "Mengurangi Risiko"),
  R(29, "Pembelajaran Asinkronus", "Belum semua fasilitator mengoptimalkan pembelajaran Asinkronus", "Kurangnya pemahaman tentang konsep pembelajaran asinkronus; kurangnya keterampilan dalam merancang materi pembelajaran asinkronus", null, "Operasional", "Eksternal", "Sering Terjadi", "Moderat", "Sedang", "Menyediakan fitur di E-WARKOP untuk sesi asinkronus melalui QnA, Upload Tugas dan Kuis; menyediakan fitur breakout room di Zoom untuk forum diskusi kelompok", "kurang efektif", "Mengurangi Risiko"),
  // ===== Evaluasi =====
  R(30, "Penetapan Kelulusan peserta", "Belum terstandarnya penilaian dari fasilitator", "faktor preferensi pribadi", "Penilaian fasilitator pada setiap kelompoknya berbeda, misalnya akan ditemui nilai-nilai besar yang terkumpul dalam satu kelompok", "Operasional", "Eksternal", "Kadang Terjadi", "Minor", "Rendah", "Penyelenggara menetapkan indikator penilaian dan melakukan kalibrasi nilai", "efektif", "Mengurangi Risiko"),
  R(31, "Seluruh peserta telah lengkap mengisi evaluasi (penyelenggaraan dan fasilitator) pada hari terakhir PJJ", "Data Evaluasi tidak lengkap terisi", "Kurangnya pemahaman peserta akan urgensi dari evaluasi", "Menyulitkan penyelenggara untuk menganalisis dengan tepat", "Operasional", "Eksternal", "Sering Terjadi", "Moderat", "Tinggi", "Manajer kelas sudah mengingatkan pada peserta untuk mengisi evaluasi", "kurang efektif", "Mengurangi Risiko"),
  R(32, "PIC/Manajer Kelas memeriksa kelengkapan administrasi fasilitator, maksimal H+5", "Keterlambatan dalam pengumpulan dokumen administrasi", "Fasilitator kurang mendapatkan informasi terkait kelengkapan administrasi yang harus dikumpulkan", "Proses verifikasi dokumen administrasi dan pencairannya menjadi tertunda", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "Manajer kelas melakukan checklist kelengkapan dokumen yang komprehensif", "efektif", "Mengurangi Risiko"),
  R(33, "Manajer Kelas/PIC mengunggah file nilai akhir ke Simdiklat", "Keterlambatan dalam pengunggahan nilai akhir", "Kompilasi nilai selama pelatihan belum difasilitasi oleh Simdiklat, sehingga penyelenggara secara manual merekap nilai dan menghitung nilai akhir", "Menghambat proses pelaporan hasil pelatihan dan e-sign sertifikat", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "Menetapkan jadwal pengunggahan yang jelas dan memastikan semua pihak terkait mematuhinya", "kurang efektif", "Mengurangi Risiko"),
  R(34, "Mengecek kelengkapan Laporan Penyelenggaraan, KAK dan SK telah diunggah di Simdiklat, maksimal H+10", "Pelaporan tidak tepat waktu", "Penyelenggara kurang memahami dokumen yang dilengkapi pada Laporan Penyelenggaraan", "Menghambat proses penilaian oleh Tim Penjaminan Mutu", "Operasional", "Internal", "Kadang Terjadi", "Minor", "Rendah", "Template laporan penyelenggaraan telah diinformasikan ke Penyelenggara", "efektif", "Mengurangi Risiko"),
  R(35, "Generate Sertifikat dan Proses e-sign", "Data peserta pada sertifikat masih terdapat kesalahan", "Peserta tidak melakukan preview pada draft sertifikat dan tidak mengisi profil peserta sesuai keadaan terkini", "Sertifikat yang sudah di e-sign, meskipun masih terdapat kesalahan namun tidak dapat diperbaiki", "Operasional", "Eksternal", "Jarang Terjadi", "Moderat", "Rendah", "PIC Pusdiklat sudah menginformasikan prosedur yang jelas pada saat Overview Pelatihan, dan Manajer Kelas mengingatkan peserta untuk preview draft sertifikat", "efektif", "Mengurangi Risiko"),
  R(36, "Membuat laporan hasil evaluasi penyelenggaraan dan pengajar yang terdapat di Simdiklat sebagai dasar Rencana Tindak Lanjut", "Data pada form evaluasi di Simdiklat belum terkumpul secara lengkap", "Evaluasi belum diisi oleh semua peserta, sehingga laporan tidak mencerminkan perspektif yang lebih luas", "Interpretasi terhadap hasil analisis data menjadi kurang tepat, sehingga kesimpulan yang diambil kurang akurat", "Operasional", "Eksternal", "Sering Terjadi", "Moderat", "Tinggi", "Penyelenggara telah menyampaikan saat Overview Pelatihan dan Manajer kelas telah menyampaikan ke peserta setiap selesai pembelajaran", "kurang efektif", "Mengurangi Risiko"),
];